import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { CheckboxComponent } from '../components/checkbox/CheckBox';
declare const _default: ComponentMeta<CheckboxComponent>;
export default _default;
export declare const DefaultChecked: ComponentStory<CheckboxComponent>;
export declare const SelectableLabel: ComponentStory<CheckboxComponent>;
export declare const Group: ComponentStory<React.ForwardRefExoticComponent<import("../components/checkbox/group").CheckboxGroupProps & React.RefAttributes<HTMLDivElement>>>;
export declare const GroupOrientation: ComponentStory<React.ForwardRefExoticComponent<import("../components/checkbox/group").CheckboxGroupProps & React.RefAttributes<HTMLDivElement>>>;
export declare const GroupDefaultSelected: ComponentStory<React.ForwardRefExoticComponent<import("../components/checkbox/group").CheckboxGroupProps & React.RefAttributes<HTMLDivElement>>>;
